curl -X POST "https://open.feishu.cn/open-apis/bot/v2/hook/70d7d8f5-0893-41ba-afc5-3ba1a2fbe486" \
-H "Content-Type: application/json; charset=utf-8" \
-d '{
      "msg_type": "text", 
      "content": {
          "text": "还有个富文本没有尝试兄弟们"
      }
    }'


### Curl 请求示例
curl https://api.openai.com/v1/chat/completions \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer YOUR_API_KEY' \
  -d '{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello!"}]
}'

### 
curl https://open.feishu.cn/open-apis/bot/v2/hook/70d7d8f5-0893-41ba-afc5-3ba1a2fbe486 \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer YOUR_API_KEY' \
  -d '{
    "msg_type": "text",
    "content": {
      "text": "嘿嘿"
    },
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello!"}]
}'